2.1: reduced image size to 89M and refactoring - use minideb as base image insted of ubuntu and removed apt lists - shellcheck fixes

diff --git a/scripts/fuf b/scripts/fuf
--- a/scripts/fuf
+++ b/scripts/fuf
@@ -1,10 +1,10 @@
    #!/bin/bash --posix
 
    # This script may need some adjustments to work on a given system.
-   # For instance, the utility `gsed` may need to be installed.
-   # Also, please be advised that `bash` (not `sh`) must be used.
+   # For instance, the utility 'gsed' may need to be installed.
+   # Also, please be advised that 'bash' (not 'sh') must be used.
 
-   # Copyright (c) 2019 IETF Trust, Kent Watsen, and Erik Auerswald.
+   # Copyright (c) 2020 IETF Trust, Kent Watsen, and Erik Auerswald.
    # All rights reserved.
    #
    # Redistribution and use in source and binary forms, with or without
@@ -27,7 +27,7 @@
    # THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    # "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
    # LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
-   # FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
+   # FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE
    # COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
    # INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
    # (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
@@ -39,8 +39,8 @@
 
    print_usage() {
      printf "\n"
-     printf "Folds or unfolds the input text file according to BCP XXX"
-     printf " (RFC XXXX).\n"
+     printf "Folds or unfolds the input text file according to"
+     printf " RFC 8792.\n"
      printf "\n"
      printf "Usage: rfcfold [-h] [-d] [-q] [-s <strategy>] [-c <col>]"
      printf " [-r] -i <infile> -o <outfile>\n"
@@ -68,8 +68,8 @@
    outfile=""
    maxcol=69  # default, may be overridden by param
    col_gvn=0  # maxcol overridden?
-   hdr_txt_1="NOTE: '\\' line wrapping per BCP XXX (RFC XXXX)"
-   hdr_txt_2="NOTE: '\\\\' line wrapping per BCP XXX (RFC XXXX)"
+   hdr_txt_1="NOTE: '\\' line wrapping per RFC 8792"
+   hdr_txt_2="NOTE: '\\\\' line wrapping per RFC 8792"
    equal_chars="======================================================="
    space_chars="                                                       "
    temp_dir=""
@@ -80,7 +80,7 @@
      if [[ "$quiet" -eq 0 ]]; then
        format_string="${prog_name}: $1: %s\n"
        shift
-       printf -- "$format_string" "$@" >&2
+       printf -- "$format_string" "$*" >&2
      fi
    }
 
@@ -102,9 +102,8 @@
    type gsed > /dev/null 2>&1 && SED=gsed || SED=sed
 
    # warn if a non-GNU sed utility is used
-   "$SED" --version < /dev/null 2> /dev/null \
-   | grep GNU > /dev/null 2>&1 || \
-   warn 'not using GNU `sed` (likely cause if an error occurs)'
+   "$SED" --version < /dev/null 2> /dev/null | grep -q GNU || \
+   warn 'not using GNU `sed` (likely cause if an error occurs).'
 
    cleanup() {
      rm -rf "$temp_dir"
@@ -114,11 +113,10 @@
    fold_it_1() {
      # ensure input file doesn't contain the fold-sequence already
      if [[ -n "$("$SED" -n '/\\$/p' "$infile")" ]]; then
-       err "infile has a line ending with a '\\' character."\
-           "This file cannot be folded using the '\\' strategy"\
+       err "infile '$infile' has a line ending with a '\\' character."\
+           "This script cannot fold this file using the '\\' strategy"\
            "without there being false positives produced in the"\
-           "unfolding (i.e., this script does not force-fold"\
-           "such lines, as described in BCP XXX, RFC XXXX)."
+           "unfolding."
        return 1
      fi
 
@@ -128,8 +126,8 @@
      # ensure input file doesn't contain whitespace on the fold column
      grep -q "^\(.\{$foldcol\}\)\{1,\} " "$infile"
      if [[ $? -eq 0 ]]; then
-       err "infile has a space character occurring on the"\
-           "folding column. This file cannot be folded using the"\
+       err "infile '$infile' has a space character occurring on the"\
+           "folding column.  This file cannot be folded using the"\
            "'\\' strategy."
        return 1
      fi
@@ -157,15 +155,13 @@
      foldcol=$(expr "$maxcol" - 1) # for the inserted '\' char
 
      # ensure input file doesn't contain the fold-sequence already
-     if [[ -n "$("$SED" -n '/\\$/{N;s/\\\n[ ]*\\/&/p}' "$infile")" ]]
+     if [[ -n "$("$SED" -n '/\\$/{N;s/\\\n[ ]*\\/&/p;D}' "$infile")" ]]
      then
-       err "infile has a line ending with a '\\' character"\
+       err "infile '$infile' has a line ending with a '\\' character"\
            "followed by a '\\' character as the first non-space"\
            "character on the next line.  This script cannot fold"\
-           "this file using '\\\\' strategy without there being"\
-           "false positives produced in the unfolding (i.e., this"\
-           "script does not force-fold such lines, as described"\
-           "in BCP XXX, RFC XXXX)."
+           "this file using the '\\\\' strategy without there being"\
+           "false positives produced in the unfolding."
        return 1
      fi
 
@@ -188,10 +184,11 @@
    }
 
    fold_it() {
-     # ensure input file doesn't contain a TAB
+     # ensure input file doesn't contain a tab
      grep -q $'\t' "$infile"
      if [[ $? -eq 0 ]]; then
-       err "infile contains a TAB character, which is not allowed."
+       err "infile '$infile' contains a tab character, which is not"\
+           "allowed."
        return 1
      fi
 
@@ -199,18 +196,20 @@
      # may result in a wrong folding column and is not supported
      if type gawk > /dev/null 2>&1; then
        env LC_ALL=C gawk '/[\000-\014\016-\037\177]/{exit 1}' "$infile"\
-       || warn 'infile contains ASCII control characters (unsupported).'
+       || warn "infile '$infile' contains ASCII control characters"\
+               "(unsupported)."
        env LC_ALL=C gawk '/[^\000-\177]/{exit 1}' "$infile"\
-       || warn 'infile contains non-ASCII characters (unsupported).'
+       || warn "infile '$infile' contains non-ASCII characters"\
+               "(unsupported)."
      else
-       dbg 'no GNU Awk, skipping checks for special characters.'
+       dbg "no GNU awk; skipping checks for special characters."
      fi
 
      # check if file needs folding
      testcol=$(expr "$maxcol" + 1)
      grep -q ".\{$testcol\}" "$infile"
      if [[ $? -ne 0 ]]; then
-       dbg "nothing to do"
+       dbg "nothing to do; copying infile to outfile."
        cp "$infile" "$outfile"
        return 255
      fi
@@ -229,7 +228,7 @@
      result=$?
      quiet="$quiet_sav"
      if [[ "$result" -ne 0 ]]; then
-       dbg "Folding strategy 1 didn't succeed, trying strategy 2..."
+       dbg "Folding strategy '1' didn't succeed; trying strategy '2'..."
        fold_it_2
        return $?
      fi
@@ -268,7 +267,7 @@
      result=$(echo "$line" | fgrep "$hdr_txt_1")
      if [[ $? -eq 0 ]]; then
        if [[ -n "$line2" ]]; then
-         err "the second line is not empty."
+         err "the second line in '$infile' is not empty."
          return 1
        fi
        unfold_it_1
@@ -277,13 +276,13 @@
      result=$(echo "$line" | fgrep "$hdr_txt_2")
      if [[ $? -eq 0 ]]; then
        if [[ -n "$line2" ]]; then
-         err "the second line is not empty."
+         err "the second line in '$infile' is not empty."
          return 1
        fi
        unfold_it_2
        return $?
      fi
-     dbg "nothing to do"
+     dbg "nothing to do; copying infile to outfile."
      cp "$infile" "$outfile"
      return 255
    }
@@ -298,43 +297,59 @@
        elif [[ "$1" == "-q" ]]; then
          quiet=1
        elif [[ "$1" == "-s" ]]; then
+         if [[ "$#" -eq "1" ]]; then
+           err "option '-s' needs an argument (use -h for help)."
+           exit 1
+         fi
          strategy="$2"
          shift
        elif [[ "$1" == "-c" ]]; then
+         if [[ "$#" -eq "1" ]]; then
+           err "option '-c' needs an argument (use -h for help)."
+           exit 1
+         fi
          col_gvn=1
          maxcol="$2"
          shift
        elif [[ "$1" == "-r" ]]; then
          reversed=1
        elif [[ "$1" == "-i" ]]; then
+         if [[ "$#" -eq "1" ]]; then
+           err "option '-i' needs an argument (use -h for help)."
+           exit 1
+         fi
          infile="$2"
          shift
        elif [[ "$1" == "-o" ]]; then
+         if [[ "$#" -eq "1" ]]; then
+           err "option '-o' needs an argument (use -h for help)."
+           exit 1
+         fi
          outfile="$2"
          shift
        else
-         warn "ignoring unknown option '$1'"
+         warn "ignoring unknown option '$1'."
        fi
        shift
      done
 
      if [[ -z "$infile" ]]; then
-       err "infile parameter missing (use -h for help)"
+       err "infile parameter missing (use -h for help)."
        exit 1
      fi
 
      if [[ -z "$outfile" ]]; then
-       err "outfile parameter missing (use -h for help)"
+       err "outfile parameter missing (use -h for help)."
        exit 1
      fi
 
      if [[ ! -f "$infile" ]]; then
-       err "specified file \"$infile\" is does not exist."
+       err "specified file '$infile' does not exist."
        exit 1
      fi
 
      if [[ "$col_gvn" -eq 1 ]] && [[ "$reversed" -eq 1 ]]; then
-       warn "'-c' option ignored when unfolding (option '-r')"
+       warn "'-c' option ignored when unfolding (option '-r')."
      fi
 
      if [[ "$strategy" -eq 0 ]] || [[ "$strategy" -eq 2 ]]; then
